[terminal]
vt = "next"

[default_session]
command = "tuigreet --remember --time --issue --asterisks --cmd sway"
user = "_greetd"
 
[initial_session]
command = "sway --config /etc/greetd/oem-setup"
user = "oem"
